[[headers]]
  for = "/*.otf"
  [headers.values]
    Content-Type = "application/font-sfnt"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Content-Type = "font/woff"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Content-Type = "font/ttf"
    Access-Control-Allow-Origin = "*"

